import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#00468d",
        "surface-variant": "#2d3449",
        "error-container": "#93000a",
        "surface-container": "#171f33",
        primary: "#ebffe2",
        "on-surface": "#dae2fd",
        "on-primary-container": "#007117",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001b3e",
        tertiary: "#f9f8ff",
        "primary-fixed-dim": "#00e639",
        "surface-tint": "#00e639",
        "secondary-fixed-dim": "#ffb4ab",
        "surface-container-lowest": "#060e20",
        "secondary-fixed": "#ffdad6",
        error: "#ffb4ab",
        "on-secondary": "#690006",
        "primary-fixed": "#72ff70",
        "on-tertiary-container": "#005fbc",
        "on-secondary-fixed-variant": "#93000c",
        outline: "#84967e",
        "surface-dim": "#0b1326",
        "primary-container": "#00ff41",
        surface: "#0b1326",
        "surface-container-highest": "#2d3449",
        "on-primary-fixed-variant": "#00530e",
        "inverse-on-surface": "#283044",
        "on-background": "#dae2fd",
        "on-primary": "#003907",
        "on-primary-fixed": "#002203",
        secondary: "#ffb4ab",
        "surface-container-low": "#131b2e",
        "tertiary-fixed-dim": "#aac7ff",
        "tertiary-container": "#cdddff",
        "tertiary-fixed": "#d6e3ff",
        background: "#0b1326",
        "inverse-primary": "#006e16",
        "on-surface-variant": "#b9ccb2",
        "on-tertiary": "#003064",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "on-secondary-fixed": "#410002",
        "on-secondary-container": "#ffe2de",
        "outline-variant": "#3b4b37",
        "surface-bright": "#31394d",
        "secondary-container": "#d30017",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xl: "64px",
        sm: "12px",
        xs: "4px",
        md: "24px",
        "margin-mobile": "16px",
        lg: "40px",
        "margin-desktop": "32px",
        gutter: "16px",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.5", fontWeight: "400" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", fontWeight: "500" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-mono": [
          "14px",
          { lineHeight: "1.0", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      animation: {
        "bounce-slow": "bounce 3s infinite",
      },
    },
  },
  plugins: [],
};
export default config;
